language: python
sudo: required
dist: trusty
services:
  - docker
os:
  - linux
env:
  - JOB=check_style
script:
  - docker run -it -v $PWD:/work -w /work pytorch/pytorch:latest ./scripts/build.sh ${JOB}
notifications:
  email:
    on_success: change
    on_failure: always
